/********************
Copyright Notice
Copyright © 2019, The Regents of the University of California
All rights reserved.

Please see the file LICENSE in this distribution for license terms.
**********************/
using System;
using System.Collections.Generic;
using System.Text;
using Caliburn.Micro;
using MathWorks.MATLAB.NET.Arrays;
using MathWorks.MATLAB.NET.Utility;
using PlotFigure_wFunctionsCom;

/// <summary>
/// Sample driver code that integrates a compiled MATLAB function
/// generated by MATLAB Compiler SDK
///
/// Refer to the MATLAB Compiler SDK documentation for more
/// information.
/// </summary>
class HideFigureSample1 {

	static Class1 class1Instance;

    public static void Setup() {
		class1Instance = new Class1();
    }

	/// <summary>
	/// Example of using the HideFigure function.
	/// </summary>
	public static void HideFigureSample(ILog _log) {
		try {
			class1Instance.HideFigure();
		} catch (Exception e) {
            _log.Error(e);
		}
	}
}
