/********************
Copyright Notice
Copyright © 2019, The Regents of the University of California
All rights reserved.

Please see the file LICENSE in this distribution for license terms.
**********************/
using System;
using System.Collections.Generic;
using System.Text;
using MathWorks.MATLAB.NET.Arrays;
using MathWorks.MATLAB.NET.Utility;
using PlotFigure_wFunctionsCom;

/// <summary>
/// Sample driver code that integrates a compiled MATLAB function
/// generated by MATLAB Compiler SDK
///
/// Refer to the MATLAB Compiler SDK documentation for more
/// information.
/// </summary>
class PlotDataSample1 {

	static Class1 class1Instance;

	public static void Setup() {
		class1Instance = new Class1();
	}

	/// <summary>
	/// Example of using the PlotData function.
	/// </summary>
	public static void PlotDataSample(double xInData, double yInData) {
		try {
			MWNumericArray xIn = new MWNumericArray(xInData);
			MWNumericArray yIn = new MWNumericArray(yInData);
			class1Instance.PlotData(xIn, yIn);
		} catch (Exception e) {
			Console.WriteLine(e);
		}
	}
}
